SET NAMES utf8mb4;
-- Additive migration. Run before deploying the report-first AI service.
SET @q = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema='askxuan_ai' AND table_name='ai_report' AND column_name='document_json')=0,'ALTER TABLE askxuan_ai.ai_report ADD COLUMN document_json MEDIUMTEXT NULL','SELECT 1');
PREPARE stmt FROM @q; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @q = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema='askxuan_ai' AND table_name='ai_report' AND column_name='generation_stage')=0,"ALTER TABLE askxuan_ai.ai_report ADD COLUMN generation_stage VARCHAR(32) NOT NULL DEFAULT ''",'SELECT 1');
PREPARE stmt FROM @q; EXECUTE stmt; DEALLOCATE PREPARE stmt;

INSERT IGNORE INTO askxuan_ai.ai_skill(code,name,description,prompt_template,input_schema,capabilities,tool_config,sort_order) VALUES('naming','姓名学','从音、形、义开始，比较名字与命名方向','提供中文名字的音形义分析与候选比较。不编造康熙笔画、五格吉凶、古籍出处、商标查询结果或姓名分数。','{"fields": [{"key": "mode", "label": "使用方式", "type": "select", "required": true, "options": [{"value": "review", "label": "评名"}, {"value": "create", "label": "起名"}]}, {"key": "surname", "label": "姓氏或品牌主体", "type": "text", "required": true}, {"key": "name", "label": "已有名字", "type": "text", "required": false}, {"key": "preferences", "label": "偏好与避用字", "type": "text", "required": false}]}','["report", "structured_input"]','{"enabled": false}',180);
INSERT IGNORE INTO askxuan_ai.ai_report_product(code,title,subtitle,chapters_json,version) VALUES('naming','姓名学','从音、形、义开始，比较名字与命名方向','["命名背景", "读音与字形", "字义与文化联想", "候选比较", "使用前核对"]','2.0');

INSERT IGNORE INTO askxuan_ai.ai_skill(code,name,description,prompt_template,input_schema,capabilities,tool_config,sort_order) VALUES('dream','周公解梦','记录梦境，从意象与感受整理线索','解释梦境的文化意象和可能的现实联想。不得作诊断或把梦解释为灾祸预告。传统意象与个人联想分开，不能假造典籍引用。','{"fields": [{"key": "dream", "label": "梦境内容", "type": "text", "required": true}, {"key": "feeling", "label": "醒来后的感受", "type": "text", "required": false}]}','["report", "structured_input"]','{"enabled": false}',181);
INSERT IGNORE INTO askxuan_ai.ai_report_product(code,title,subtitle,chapters_json,version) VALUES('dream','周公解梦','记录梦境，从意象与感受整理线索','["梦境线索", "意象整理", "传统文化视角", "情绪与现实联系", "记录与行动"]','2.0');

INSERT IGNORE INTO askxuan_ai.ai_skill(code,name,description,prompt_template,input_schema,capabilities,tool_config,sort_order) VALUES('date_select','择日通书','对照备选日期的黄历，安排重要事项','依据实际黄历工具输出比较用户明确选择的日期。黄历宜忌缺少相关事项时写未列出，不能编造吉日分数或保证成功。','{"fields": [{"key": "event", "label": "准备安排的事项", "type": "text", "required": true}, {"key": "targetDate", "label": "备选日期一", "type": "date", "required": true}, {"key": "secondDate", "label": "备选日期二", "type": "date", "required": false}, {"key": "thirdDate", "label": "备选日期三", "type": "date", "required": false}]}','["report", "structured_input"]','{"enabled": false}',182);
INSERT IGNORE INTO askxuan_ai.ai_report_product(code,title,subtitle,chapters_json,version) VALUES('date_select','择日通书','对照备选日期的黄历，安排重要事项','["日期与事项", "黄历对照", "现实安排", "方案比较", "执行清单"]','2.0');

INSERT IGNORE INTO askxuan_ai.ai_skill(code,name,description,prompt_template,input_schema,capabilities,tool_config,sort_order) VALUES('fortune','每日运势','查看当日黄历，整理今天的关注与计划','把每日运势定位为黄历文化参考和每日计划，不生成个人吉凶评分、财运概率或幸运数预测。','{"fields": [{"key": "targetDate", "label": "查看日期", "type": "date", "required": true}, {"key": "focus", "label": "今天最关心的事", "type": "text", "required": false}]}','["report", "structured_input"]','{"enabled": false}',183);
INSERT IGNORE INTO askxuan_ai.ai_report_product(code,title,subtitle,chapters_json,version) VALUES('fortune','每日运势','查看当日黄历，整理今天的关注与计划','["今日历法", "今天的关注", "工作与生活", "可行行动", "晚间回顾"]','2.0');

INSERT IGNORE INTO askxuan_ai.ai_skill(code,name,description,prompt_template,input_schema,capabilities,tool_config,sort_order) VALUES('face_palm','面相手相','辨识可见特征，了解传统图解术语','只描述照片中直接可见的外观、线条与位置，并介绍相应文化术语。严禁根据面部或掌纹推断人格、品德、健康、疾病、智力、性别认同、种族、命运或社会身份；不做人脸识别。','{"fields": [{"key": "mode", "label": "图解类型", "type": "select", "required": true, "options": [{"value": "face", "label": "面部可见特征"}, {"value": "palm", "label": "掌纹可见线条"}]}]}','["report", "structured_input"]','{"enabled": false}',184);
INSERT IGNORE INTO askxuan_ai.ai_report_product(code,title,subtitle,chapters_json,version) VALUES('face_palm','面相手相','辨识可见特征，了解传统图解术语','["图片观察范围", "可见特征", "传统术语图解", "无法确定的内容", "延伸阅读"]','2.0');

UPDATE askxuan_ai.ai_report_product SET title='八字排盘',subtitle='四柱命盘、五行分布与大运流年，形成一份完整解读',chapters_json='["资料与排盘依据", "四柱与五行", "大运与流年", "事业与发展", "关系与相处", "行动清单"]',version='2.0' WHERE code='bazi';
UPDATE askxuan_ai.ai_report_product SET title='周易占卜',subtitle='从六爻盘面看当下处境，梳理变化与行动',version='2.0' WHERE code='liuyao';

-- Both participants are calculated independently; no invented compatibility score.
UPDATE askxuan_ai.ai_skill SET input_schema='{"fields": [{"key": "calendarType", "label": "你的历法", "type": "select", "required": true, "options": [{"value": "solar", "label": "公历"}, {"value": "lunar", "label": "农历"}], "defaultValue": "solar", "helpText": "按已确认的出生资料填写；不确定时请先核对，系统不会猜测。"}, {"key": "birthDate", "label": "你的出生日期", "type": "date", "required": true, "helpText": "按已确认的出生资料填写；不确定时请先核对，系统不会猜测。"}, {"key": "birthTime", "label": "你的出生时间", "type": "time", "required": true, "helpText": "按已确认的出生资料填写；不确定时请先核对，系统不会猜测。"}, {"key": "gender", "label": "你的性别", "type": "select", "required": true, "options": [{"value": "male", "label": "男"}, {"value": "female", "label": "女"}], "helpText": "按已确认的出生资料填写；不确定时请先核对，系统不会猜测。"}, {"key": "partnerCalendarType", "label": "对方的历法", "type": "select", "required": true, "options": [{"value": "solar", "label": "公历"}, {"value": "lunar", "label": "农历"}], "defaultValue": "solar", "helpText": "按已确认的出生资料填写；不确定时请先核对，系统不会猜测。"}, {"key": "partnerBirthDate", "label": "对方的出生日期", "type": "date", "required": true, "helpText": "按已确认的出生资料填写；不确定时请先核对，系统不会猜测。"}, {"key": "partnerBirthTime", "label": "对方的出生时间", "type": "time", "required": true, "helpText": "按已确认的出生资料填写；不确定时请先核对，系统不会猜测。"}, {"key": "partnerGender", "label": "对方的性别", "type": "select", "required": true, "options": [{"value": "male", "label": "男"}, {"value": "female", "label": "女"}], "helpText": "按已确认的出生资料填写；不确定时请先核对，系统不会猜测。"}]}',prompt_template='依据双方各自的八字工具结果并列解释传统文化关系，必须区分你的资料与对方资料；不编造匹配百分比，不断言关系结局。结合用户描述提出可讨论、可核对的相处建议。',version='2.0.0' WHERE code='marriage';
UPDATE askxuan_ai.ai_report_product SET subtitle='双方独立排盘、并列对照，再讨论相处与沟通',chapters_json='["双方资料与命盘","五行与关系对照","相处中的关注","沟通与分歧","共同计划"]',version='2.0' WHERE code='marriage';
