// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: rpc/shoporder/shop_order.proto

package shoporder

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidatePaymentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatePaymentReq) Reset() {
	*x = ValidatePaymentReq{}
	mi := &file_rpc_shoporder_shop_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePaymentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePaymentReq) ProtoMessage() {}

func (x *ValidatePaymentReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_shoporder_shop_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePaymentReq.ProtoReflect.Descriptor instead.
func (*ValidatePaymentReq) Descriptor() ([]byte, []int) {
	return file_rpc_shoporder_shop_order_proto_rawDescGZIP(), []int{0}
}

func (x *ValidatePaymentReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *ValidatePaymentReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidatePaymentReq) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ValidatedShopOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PayAmount     float64                `protobuf:"fixed64,4,opt,name=pay_amount,json=payAmount,proto3" json:"pay_amount,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatedShopOrder) Reset() {
	*x = ValidatedShopOrder{}
	mi := &file_rpc_shoporder_shop_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatedShopOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatedShopOrder) ProtoMessage() {}

func (x *ValidatedShopOrder) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_shoporder_shop_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatedShopOrder.ProtoReflect.Descriptor instead.
func (*ValidatedShopOrder) Descriptor() ([]byte, []int) {
	return file_rpc_shoporder_shop_order_proto_rawDescGZIP(), []int{1}
}

func (x *ValidatedShopOrder) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ValidatedShopOrder) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *ValidatedShopOrder) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidatedShopOrder) GetPayAmount() float64 {
	if x != nil {
		return x.PayAmount
	}
	return 0
}

func (x *ValidatedShopOrder) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_rpc_shoporder_shop_order_proto protoreflect.FileDescriptor

const file_rpc_shoporder_shop_order_proto_rawDesc = "" +
	"\n" +
	"\x1erpc/shoporder/shop_order.proto\x12\tshoporder\"`\n" +
	"\x12ValidatePaymentReq\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\"\x8f\x01\n" +
	"\x12ValidatedShopOrder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"pay_amount\x18\x04 \x01(\x01R\tpayAmount\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status2c\n" +
	"\x10ShopOrderService\x12O\n" +
	"\x0fValidatePayment\x12\x1d.shoporder.ValidatePaymentReq\x1a\x1d.shoporder.ValidatedShopOrderB3Z1github.com/askxuan/common/rpc/shoporder;shoporderb\x06proto3"

var (
	file_rpc_shoporder_shop_order_proto_rawDescOnce sync.Once
	file_rpc_shoporder_shop_order_proto_rawDescData []byte
)

func file_rpc_shoporder_shop_order_proto_rawDescGZIP() []byte {
	file_rpc_shoporder_shop_order_proto_rawDescOnce.Do(func() {
		file_rpc_shoporder_shop_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_shoporder_shop_order_proto_rawDesc), len(file_rpc_shoporder_shop_order_proto_rawDesc)))
	})
	return file_rpc_shoporder_shop_order_proto_rawDescData
}

var file_rpc_shoporder_shop_order_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_shoporder_shop_order_proto_goTypes = []any{
	(*ValidatePaymentReq)(nil), // 0: shoporder.ValidatePaymentReq
	(*ValidatedShopOrder)(nil), // 1: shoporder.ValidatedShopOrder
}
var file_rpc_shoporder_shop_order_proto_depIdxs = []int32{
	0, // 0: shoporder.ShopOrderService.ValidatePayment:input_type -> shoporder.ValidatePaymentReq
	1, // 1: shoporder.ShopOrderService.ValidatePayment:output_type -> shoporder.ValidatedShopOrder
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_shoporder_shop_order_proto_init() }
func file_rpc_shoporder_shop_order_proto_init() {
	if File_rpc_shoporder_shop_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_shoporder_shop_order_proto_rawDesc), len(file_rpc_shoporder_shop_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_shoporder_shop_order_proto_goTypes,
		DependencyIndexes: file_rpc_shoporder_shop_order_proto_depIdxs,
		MessageInfos:      file_rpc_shoporder_shop_order_proto_msgTypes,
	}.Build()
	File_rpc_shoporder_shop_order_proto = out.File
	file_rpc_shoporder_shop_order_proto_goTypes = nil
	file_rpc_shoporder_shop_order_proto_depIdxs = nil
}
