// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: rpc/shoporder/shop_order.proto

package shoporder

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShopOrderService_ValidatePayment_FullMethodName = "/shoporder.ShopOrderService/ValidatePayment"
)

// ShopOrderServiceClient is the client API for ShopOrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShopOrderServiceClient interface {
	ValidatePayment(ctx context.Context, in *ValidatePaymentReq, opts ...grpc.CallOption) (*ValidatedShopOrder, error)
}

type shopOrderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShopOrderServiceClient(cc grpc.ClientConnInterface) ShopOrderServiceClient {
	return &shopOrderServiceClient{cc}
}

func (c *shopOrderServiceClient) ValidatePayment(ctx context.Context, in *ValidatePaymentReq, opts ...grpc.CallOption) (*ValidatedShopOrder, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidatedShopOrder)
	err := c.cc.Invoke(ctx, ShopOrderService_ValidatePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShopOrderServiceServer is the server API for ShopOrderService service.
// All implementations must embed UnimplementedShopOrderServiceServer
// for forward compatibility.
type ShopOrderServiceServer interface {
	ValidatePayment(context.Context, *ValidatePaymentReq) (*ValidatedShopOrder, error)
	mustEmbedUnimplementedShopOrderServiceServer()
}

// UnimplementedShopOrderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShopOrderServiceServer struct{}

func (UnimplementedShopOrderServiceServer) ValidatePayment(context.Context, *ValidatePaymentReq) (*ValidatedShopOrder, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidatePayment not implemented")
}
func (UnimplementedShopOrderServiceServer) mustEmbedUnimplementedShopOrderServiceServer() {}
func (UnimplementedShopOrderServiceServer) testEmbeddedByValue()                          {}

// UnsafeShopOrderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShopOrderServiceServer will
// result in compilation errors.
type UnsafeShopOrderServiceServer interface {
	mustEmbedUnimplementedShopOrderServiceServer()
}

func RegisterShopOrderServiceServer(s grpc.ServiceRegistrar, srv ShopOrderServiceServer) {
	// If the following call panics, it indicates UnimplementedShopOrderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShopOrderService_ServiceDesc, srv)
}

func _ShopOrderService_ValidatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidatePaymentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopOrderServiceServer).ValidatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopOrderService_ValidatePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopOrderServiceServer).ValidatePayment(ctx, req.(*ValidatePaymentReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ShopOrderService_ServiceDesc is the grpc.ServiceDesc for ShopOrderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShopOrderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shoporder.ShopOrderService",
	HandlerType: (*ShopOrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidatePayment",
			Handler:    _ShopOrderService_ValidatePayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/shoporder/shop_order.proto",
}
