// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/diy.proto

package diy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BlessingTask 加持任务（对应 askxuan_diy.blessing_task 表）
type BlessingTask struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskNo          string                 `protobuf:"bytes,2,opt,name=task_no,json=taskNo,proto3" json:"task_no,omitempty"`
	DiyOrderNo      string                 `protobuf:"bytes,3,opt,name=diy_order_no,json=diyOrderNo,proto3" json:"diy_order_no,omitempty"`
	TempleCode      string                 `protobuf:"bytes,4,opt,name=temple_code,json=templeCode,proto3" json:"temple_code,omitempty"`
	MasterCode      string                 `protobuf:"bytes,5,opt,name=master_code,json=masterCode,proto3" json:"master_code,omitempty"`
	Status          string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`                                          // dispatched/assigned/accepted/in_progress/completed/rejected
	CertificateUrls string                 `protobuf:"bytes,7,opt,name=certificate_urls,json=certificateUrls,proto3" json:"certificate_urls,omitempty"` // JSON array string
	AssignTime      string                 `protobuf:"bytes,8,opt,name=assign_time,json=assignTime,proto3" json:"assign_time,omitempty"`
	CompleteTime    string                 `protobuf:"bytes,9,opt,name=complete_time,json=completeTime,proto3" json:"complete_time,omitempty"`
	CreateTime      string                 `protobuf:"bytes,10,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime      string                 `protobuf:"bytes,11,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BlessingTask) Reset() {
	*x = BlessingTask{}
	mi := &file_api_diy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlessingTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlessingTask) ProtoMessage() {}

func (x *BlessingTask) ProtoReflect() protoreflect.Message {
	mi := &file_api_diy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlessingTask.ProtoReflect.Descriptor instead.
func (*BlessingTask) Descriptor() ([]byte, []int) {
	return file_api_diy_proto_rawDescGZIP(), []int{0}
}

func (x *BlessingTask) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BlessingTask) GetTaskNo() string {
	if x != nil {
		return x.TaskNo
	}
	return ""
}

func (x *BlessingTask) GetDiyOrderNo() string {
	if x != nil {
		return x.DiyOrderNo
	}
	return ""
}

func (x *BlessingTask) GetTempleCode() string {
	if x != nil {
		return x.TempleCode
	}
	return ""
}

func (x *BlessingTask) GetMasterCode() string {
	if x != nil {
		return x.MasterCode
	}
	return ""
}

func (x *BlessingTask) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BlessingTask) GetCertificateUrls() string {
	if x != nil {
		return x.CertificateUrls
	}
	return ""
}

func (x *BlessingTask) GetAssignTime() string {
	if x != nil {
		return x.AssignTime
	}
	return ""
}

func (x *BlessingTask) GetCompleteTime() string {
	if x != nil {
		return x.CompleteTime
	}
	return ""
}

func (x *BlessingTask) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *BlessingTask) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

type GetBlessingTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlessingTaskReq) Reset() {
	*x = GetBlessingTaskReq{}
	mi := &file_api_diy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlessingTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlessingTaskReq) ProtoMessage() {}

func (x *GetBlessingTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_diy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlessingTaskReq.ProtoReflect.Descriptor instead.
func (*GetBlessingTaskReq) Descriptor() ([]byte, []int) {
	return file_api_diy_proto_rawDescGZIP(), []int{1}
}

func (x *GetBlessingTaskReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetBlessingTaskByOrderNoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiyOrderNo    string                 `protobuf:"bytes,1,opt,name=diy_order_no,json=diyOrderNo,proto3" json:"diy_order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlessingTaskByOrderNoReq) Reset() {
	*x = GetBlessingTaskByOrderNoReq{}
	mi := &file_api_diy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlessingTaskByOrderNoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlessingTaskByOrderNoReq) ProtoMessage() {}

func (x *GetBlessingTaskByOrderNoReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_diy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlessingTaskByOrderNoReq.ProtoReflect.Descriptor instead.
func (*GetBlessingTaskByOrderNoReq) Descriptor() ([]byte, []int) {
	return file_api_diy_proto_rawDescGZIP(), []int{2}
}

func (x *GetBlessingTaskByOrderNoReq) GetDiyOrderNo() string {
	if x != nil {
		return x.DiyOrderNo
	}
	return ""
}

type GetBlessingTaskByTaskNoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskNo        string                 `protobuf:"bytes,1,opt,name=task_no,json=taskNo,proto3" json:"task_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlessingTaskByTaskNoReq) Reset() {
	*x = GetBlessingTaskByTaskNoReq{}
	mi := &file_api_diy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlessingTaskByTaskNoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlessingTaskByTaskNoReq) ProtoMessage() {}

func (x *GetBlessingTaskByTaskNoReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_diy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlessingTaskByTaskNoReq.ProtoReflect.Descriptor instead.
func (*GetBlessingTaskByTaskNoReq) Descriptor() ([]byte, []int) {
	return file_api_diy_proto_rawDescGZIP(), []int{3}
}

func (x *GetBlessingTaskByTaskNoReq) GetTaskNo() string {
	if x != nil {
		return x.TaskNo
	}
	return ""
}

type ListBlessingTasksReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MasterCode    string                 `protobuf:"bytes,1,opt,name=master_code,json=masterCode,proto3" json:"master_code,omitempty"`
	TempleCode    string                 `protobuf:"bytes,2,opt,name=temple_code,json=templeCode,proto3" json:"temple_code,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Page          int64                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlessingTasksReq) Reset() {
	*x = ListBlessingTasksReq{}
	mi := &file_api_diy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlessingTasksReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlessingTasksReq) ProtoMessage() {}

func (x *ListBlessingTasksReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_diy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlessingTasksReq.ProtoReflect.Descriptor instead.
func (*ListBlessingTasksReq) Descriptor() ([]byte, []int) {
	return file_api_diy_proto_rawDescGZIP(), []int{4}
}

func (x *ListBlessingTasksReq) GetMasterCode() string {
	if x != nil {
		return x.MasterCode
	}
	return ""
}

func (x *ListBlessingTasksReq) GetTempleCode() string {
	if x != nil {
		return x.TempleCode
	}
	return ""
}

func (x *ListBlessingTasksReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListBlessingTasksReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBlessingTasksReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListBlessingTasksResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*BlessingTask        `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlessingTasksResp) Reset() {
	*x = ListBlessingTasksResp{}
	mi := &file_api_diy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlessingTasksResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlessingTasksResp) ProtoMessage() {}

func (x *ListBlessingTasksResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_diy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlessingTasksResp.ProtoReflect.Descriptor instead.
func (*ListBlessingTasksResp) Descriptor() ([]byte, []int) {
	return file_api_diy_proto_rawDescGZIP(), []int{5}
}

func (x *ListBlessingTasksResp) GetTasks() []*BlessingTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListBlessingTasksResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateBlessingTaskStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBlessingTaskStatusReq) Reset() {
	*x = UpdateBlessingTaskStatusReq{}
	mi := &file_api_diy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBlessingTaskStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBlessingTaskStatusReq) ProtoMessage() {}

func (x *UpdateBlessingTaskStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_diy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBlessingTaskStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateBlessingTaskStatusReq) Descriptor() ([]byte, []int) {
	return file_api_diy_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateBlessingTaskStatusReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateBlessingTaskStatusReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CompleteBlessingTaskReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CertificateUrls string                 `protobuf:"bytes,2,opt,name=certificate_urls,json=certificateUrls,proto3" json:"certificate_urls,omitempty"` // JSON array string
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CompleteBlessingTaskReq) Reset() {
	*x = CompleteBlessingTaskReq{}
	mi := &file_api_diy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteBlessingTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteBlessingTaskReq) ProtoMessage() {}

func (x *CompleteBlessingTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_diy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteBlessingTaskReq.ProtoReflect.Descriptor instead.
func (*CompleteBlessingTaskReq) Descriptor() ([]byte, []int) {
	return file_api_diy_proto_rawDescGZIP(), []int{7}
}

func (x *CompleteBlessingTaskReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CompleteBlessingTaskReq) GetCertificateUrls() string {
	if x != nil {
		return x.CertificateUrls
	}
	return ""
}

type AssignBlessingTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MasterCode    string                 `protobuf:"bytes,2,opt,name=master_code,json=masterCode,proto3" json:"master_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignBlessingTaskReq) Reset() {
	*x = AssignBlessingTaskReq{}
	mi := &file_api_diy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignBlessingTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignBlessingTaskReq) ProtoMessage() {}

func (x *AssignBlessingTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_diy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignBlessingTaskReq.ProtoReflect.Descriptor instead.
func (*AssignBlessingTaskReq) Descriptor() ([]byte, []int) {
	return file_api_diy_proto_rawDescGZIP(), []int{8}
}

func (x *AssignBlessingTaskReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AssignBlessingTaskReq) GetMasterCode() string {
	if x != nil {
		return x.MasterCode
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_diy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_diy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_diy_proto_rawDescGZIP(), []int{9}
}

var File_api_diy_proto protoreflect.FileDescriptor

const file_api_diy_proto_rawDesc = "" +
	"\n" +
	"\rapi/diy.proto\x12\x03diy\"\xe6\x02\n" +
	"\fBlessingTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\atask_no\x18\x02 \x01(\tR\x06taskNo\x12 \n" +
	"\fdiy_order_no\x18\x03 \x01(\tR\n" +
	"diyOrderNo\x12\x1f\n" +
	"\vtemple_code\x18\x04 \x01(\tR\n" +
	"templeCode\x12\x1f\n" +
	"\vmaster_code\x18\x05 \x01(\tR\n" +
	"masterCode\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12)\n" +
	"\x10certificate_urls\x18\a \x01(\tR\x0fcertificateUrls\x12\x1f\n" +
	"\vassign_time\x18\b \x01(\tR\n" +
	"assignTime\x12#\n" +
	"\rcomplete_time\x18\t \x01(\tR\fcompleteTime\x12\x1f\n" +
	"\vcreate_time\x18\n" +
	" \x01(\tR\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\v \x01(\tR\n" +
	"updateTime\"$\n" +
	"\x12GetBlessingTaskReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"?\n" +
	"\x1bGetBlessingTaskByOrderNoReq\x12 \n" +
	"\fdiy_order_no\x18\x01 \x01(\tR\n" +
	"diyOrderNo\"5\n" +
	"\x1aGetBlessingTaskByTaskNoReq\x12\x17\n" +
	"\atask_no\x18\x01 \x01(\tR\x06taskNo\"\xa1\x01\n" +
	"\x14ListBlessingTasksReq\x12\x1f\n" +
	"\vmaster_code\x18\x01 \x01(\tR\n" +
	"masterCode\x12\x1f\n" +
	"\vtemple_code\x18\x02 \x01(\tR\n" +
	"templeCode\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x03R\bpageSize\"V\n" +
	"\x15ListBlessingTasksResp\x12'\n" +
	"\x05tasks\x18\x01 \x03(\v2\x11.diy.BlessingTaskR\x05tasks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"E\n" +
	"\x1bUpdateBlessingTaskStatusReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"T\n" +
	"\x17CompleteBlessingTaskReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12)\n" +
	"\x10certificate_urls\x18\x02 \x01(\tR\x0fcertificateUrls\"H\n" +
	"\x15AssignBlessingTaskReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vmaster_code\x18\x02 \x01(\tR\n" +
	"masterCode\"\a\n" +
	"\x05Empty2\x96\x04\n" +
	"\n" +
	"DiyService\x12=\n" +
	"\x0fGetBlessingTask\x12\x17.diy.GetBlessingTaskReq\x1a\x11.diy.BlessingTask\x12O\n" +
	"\x18GetBlessingTaskByOrderNo\x12 .diy.GetBlessingTaskByOrderNoReq\x1a\x11.diy.BlessingTask\x12M\n" +
	"\x17GetBlessingTaskByTaskNo\x12\x1f.diy.GetBlessingTaskByTaskNoReq\x1a\x11.diy.BlessingTask\x12J\n" +
	"\x11ListBlessingTasks\x12\x19.diy.ListBlessingTasksReq\x1a\x1a.diy.ListBlessingTasksResp\x12O\n" +
	"\x18UpdateBlessingTaskStatus\x12 .diy.UpdateBlessingTaskStatusReq\x1a\x11.diy.BlessingTask\x12G\n" +
	"\x14CompleteBlessingTask\x12\x1c.diy.CompleteBlessingTaskReq\x1a\x11.diy.BlessingTask\x12C\n" +
	"\x12AssignBlessingTask\x12\x1a.diy.AssignBlessingTaskReq\x1a\x11.diy.BlessingTaskB\vZ\t./diy;diyb\x06proto3"

var (
	file_api_diy_proto_rawDescOnce sync.Once
	file_api_diy_proto_rawDescData []byte
)

func file_api_diy_proto_rawDescGZIP() []byte {
	file_api_diy_proto_rawDescOnce.Do(func() {
		file_api_diy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_diy_proto_rawDesc), len(file_api_diy_proto_rawDesc)))
	})
	return file_api_diy_proto_rawDescData
}

var file_api_diy_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_diy_proto_goTypes = []any{
	(*BlessingTask)(nil),                // 0: diy.BlessingTask
	(*GetBlessingTaskReq)(nil),          // 1: diy.GetBlessingTaskReq
	(*GetBlessingTaskByOrderNoReq)(nil), // 2: diy.GetBlessingTaskByOrderNoReq
	(*GetBlessingTaskByTaskNoReq)(nil),  // 3: diy.GetBlessingTaskByTaskNoReq
	(*ListBlessingTasksReq)(nil),        // 4: diy.ListBlessingTasksReq
	(*ListBlessingTasksResp)(nil),       // 5: diy.ListBlessingTasksResp
	(*UpdateBlessingTaskStatusReq)(nil), // 6: diy.UpdateBlessingTaskStatusReq
	(*CompleteBlessingTaskReq)(nil),     // 7: diy.CompleteBlessingTaskReq
	(*AssignBlessingTaskReq)(nil),       // 8: diy.AssignBlessingTaskReq
	(*Empty)(nil),                       // 9: diy.Empty
}
var file_api_diy_proto_depIdxs = []int32{
	0, // 0: diy.ListBlessingTasksResp.tasks:type_name -> diy.BlessingTask
	1, // 1: diy.DiyService.GetBlessingTask:input_type -> diy.GetBlessingTaskReq
	2, // 2: diy.DiyService.GetBlessingTaskByOrderNo:input_type -> diy.GetBlessingTaskByOrderNoReq
	3, // 3: diy.DiyService.GetBlessingTaskByTaskNo:input_type -> diy.GetBlessingTaskByTaskNoReq
	4, // 4: diy.DiyService.ListBlessingTasks:input_type -> diy.ListBlessingTasksReq
	6, // 5: diy.DiyService.UpdateBlessingTaskStatus:input_type -> diy.UpdateBlessingTaskStatusReq
	7, // 6: diy.DiyService.CompleteBlessingTask:input_type -> diy.CompleteBlessingTaskReq
	8, // 7: diy.DiyService.AssignBlessingTask:input_type -> diy.AssignBlessingTaskReq
	0, // 8: diy.DiyService.GetBlessingTask:output_type -> diy.BlessingTask
	0, // 9: diy.DiyService.GetBlessingTaskByOrderNo:output_type -> diy.BlessingTask
	0, // 10: diy.DiyService.GetBlessingTaskByTaskNo:output_type -> diy.BlessingTask
	5, // 11: diy.DiyService.ListBlessingTasks:output_type -> diy.ListBlessingTasksResp
	0, // 12: diy.DiyService.UpdateBlessingTaskStatus:output_type -> diy.BlessingTask
	0, // 13: diy.DiyService.CompleteBlessingTask:output_type -> diy.BlessingTask
	0, // 14: diy.DiyService.AssignBlessingTask:output_type -> diy.BlessingTask
	8, // [8:15] is the sub-list for method output_type
	1, // [1:8] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_diy_proto_init() }
func file_api_diy_proto_init() {
	if File_api_diy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_diy_proto_rawDesc), len(file_api_diy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_diy_proto_goTypes,
		DependencyIndexes: file_api_diy_proto_depIdxs,
		MessageInfos:      file_api_diy_proto_msgTypes,
	}.Build()
	File_api_diy_proto = out.File
	file_api_diy_proto_goTypes = nil
	file_api_diy_proto_depIdxs = nil
}
