// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: master_booking.proto

package master

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MasterBookingService_GetBookingMaster_FullMethodName = "/master.MasterBookingService/GetBookingMaster"
)

// MasterBookingServiceClient is the client API for MasterBookingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MasterBookingServiceClient interface {
	GetBookingMaster(ctx context.Context, in *GetBookingMasterReq, opts ...grpc.CallOption) (*BookingMaster, error)
}

type masterBookingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMasterBookingServiceClient(cc grpc.ClientConnInterface) MasterBookingServiceClient {
	return &masterBookingServiceClient{cc}
}

func (c *masterBookingServiceClient) GetBookingMaster(ctx context.Context, in *GetBookingMasterReq, opts ...grpc.CallOption) (*BookingMaster, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookingMaster)
	err := c.cc.Invoke(ctx, MasterBookingService_GetBookingMaster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterBookingServiceServer is the server API for MasterBookingService service.
// All implementations must embed UnimplementedMasterBookingServiceServer
// for forward compatibility.
type MasterBookingServiceServer interface {
	GetBookingMaster(context.Context, *GetBookingMasterReq) (*BookingMaster, error)
	mustEmbedUnimplementedMasterBookingServiceServer()
}

// UnimplementedMasterBookingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMasterBookingServiceServer struct{}

func (UnimplementedMasterBookingServiceServer) GetBookingMaster(context.Context, *GetBookingMasterReq) (*BookingMaster, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBookingMaster not implemented")
}
func (UnimplementedMasterBookingServiceServer) mustEmbedUnimplementedMasterBookingServiceServer() {}
func (UnimplementedMasterBookingServiceServer) testEmbeddedByValue()                              {}

// UnsafeMasterBookingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MasterBookingServiceServer will
// result in compilation errors.
type UnsafeMasterBookingServiceServer interface {
	mustEmbedUnimplementedMasterBookingServiceServer()
}

func RegisterMasterBookingServiceServer(s grpc.ServiceRegistrar, srv MasterBookingServiceServer) {
	// If the following call panics, it indicates UnimplementedMasterBookingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MasterBookingService_ServiceDesc, srv)
}

func _MasterBookingService_GetBookingMaster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookingMasterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterBookingServiceServer).GetBookingMaster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterBookingService_GetBookingMaster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterBookingServiceServer).GetBookingMaster(ctx, req.(*GetBookingMasterReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MasterBookingService_ServiceDesc is the grpc.ServiceDesc for MasterBookingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MasterBookingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "master.MasterBookingService",
	HandlerType: (*MasterBookingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBookingMaster",
			Handler:    _MasterBookingService_GetBookingMaster_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "master_booking.proto",
}
