// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AnnouncementCreateReq struct {
	Title          string `json:"title"`
	Content        string `json:"content"`
	Type           string `json:"type"`
	TargetAudience string `json:"targetAudience"`
}

type AnnouncementListReq struct {
	Type           string `form:"type,optional"`
	TargetAudience string `form:"targetAudience,optional"`
	Page           int    `form:"page,default=1"`
	Size           int    `form:"size,default=20"`
}

type AnnouncementListResp struct {
	Total int64                `json:"total"`
	List  []SystemAnnouncement `json:"list"`
	Page  int                  `json:"page"`
	Size  int                  `json:"size"`
}

type AnnouncementStatusReq struct {
	Id     int64  `path:"id"`
	Status string `json:"status"` // published/offline
}

type DeleteMessageReq struct {
	Id string `path:"id"`
}

type DeviceTokenRegisterReq struct {
	UserId      string `json:"userId"`
	ClientType  string `json:"clientType"` // customer/master
	Platform    string `json:"platform"`   // ios/android
	DeviceToken string `json:"deviceToken"`
	BundleId    string `json:"bundleId,optional"`
	AppVersion  string `json:"appVersion,optional"`
}

type DeviceTokenResp struct {
	Id     int64  `json:"id"`
	Status string `json:"status"`
}

type DeviceTokenUnbindReq struct {
	UserId      string `json:"userId"`
	DeviceToken string `json:"deviceToken"`
}

type IdResp struct {
	Id int64 `json:"id"`
}

type ListReq struct {
	UserId string `form:"userId"`
	IsRead int    `form:"isRead,optional,default=-1"` // -1全部 0未读 1已读
	Page   int    `form:"page,default=1"`
	Size   int    `form:"size,default=20"`
}

type ListResp struct {
	Total int64     `json:"total"`
	List  []Message `json:"list"`
	Page  int       `json:"page"`
	Size  int       `json:"size"`
}

type Message struct {
	Id        int64  `json:"id"`
	UserId    string `json:"userId"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	BizType   string `json:"bizType"` // booking/system
	BizId     string `json:"bizId"`
	IsRead    int    `json:"isRead"` // 0未读 1已读
	CreatedAt string `json:"createdAt"`
}

type MessageTemplate struct {
	Id              int64  `json:"id"`
	Code            string `json:"code"`
	TitleTemplate   string `json:"titleTemplate"`
	ContentTemplate string `json:"contentTemplate"`
	Variables       string `json:"variables"` // JSON
	Type            string `json:"type"`      // booking/system/consult/income/audit
	CreatedAt       string `json:"createdAt"`
}

type PushReq struct {
	UserId   string `json:"userId"`
	PushType string `json:"pushType"` // app_push/sms
	Title    string `json:"title"`
	Content  string `json:"content"`
	BizType  string `json:"bizType,optional"`
	BizId    string `json:"bizId,optional"`
}

type PushResp struct {
	PushLogId int64  `json:"pushLogId"`
	Status    string `json:"status"` // pending/success/failed
}

type PushLog struct {
	Id         int64  `json:"id"`
	UserId     string `json:"userId"`
	PushType   string `json:"pushType"`
	Title      string `json:"title"`
	Content    string `json:"content"`
	Status     string `json:"status"`
	BizType    string `json:"bizType"`
	BizId      string `json:"bizId"`
	CreateTime string `json:"createTime"`
}

type PushLogListReq struct {
	UserId  string `form:"userId,optional"`
	Status  string `form:"status,optional"`
	BizType string `form:"bizType,optional"`
	Page    int    `form:"page,default=1"`
	Size    int    `form:"size,default=20"`
}

type PushLogListResp struct {
	Total int64     `json:"total"`
	List  []PushLog `json:"list"`
	Page  int       `json:"page"`
	Size  int       `json:"size"`
}

type ReadAllReq struct {
	UserId string `json:"userId"`
}

type ReadAllResp struct {
	Count int64 `json:"count"`
}

type SendMessageReq struct {
	ConversationId string `json:"conversationId"`
	UserId         string `json:"userId"`
	Content        string `json:"content"`
}

type SendMessageResp struct {
	Id int64 `json:"id"`
}

type ReadReq struct {
	Id string `path:"id"`
}

type ReadResp struct {
	Id     int64 `json:"id"`
	IsRead int   `json:"isRead"`
}

type SystemAnnouncement struct {
	Id             int64  `json:"id"`
	Title          string `json:"title"`
	Content        string `json:"content"`
	Type           string `json:"type"`           // system/activity/maintenance
	TargetAudience string `json:"targetAudience"` // all/customer/temple_admin/master
	Status         string `json:"status"`         // draft/published/offline
	PublishTime    string `json:"publishTime"`
	CreateTime     string `json:"createTime"`
}

type TemplateCreateReq struct {
	Code            string `json:"code"`
	TitleTemplate   string `json:"titleTemplate"`
	ContentTemplate string `json:"contentTemplate"`
	Variables       string `json:"variables,optional"`
	Type            string `json:"type"`
}

type TemplateListReq struct {
	Type string `form:"type,optional"`
	Page int    `form:"page,default=1"`
	Size int    `form:"size,default=20"`
}

type TemplateListResp struct {
	Total int64             `json:"total"`
	List  []MessageTemplate `json:"list"`
	Page  int               `json:"page"`
	Size  int               `json:"size"`
}

type TemplateUpdateReq struct {
	Id              int64  `path:"id"`
	TitleTemplate   string `json:"titleTemplate,optional"`
	ContentTemplate string `json:"contentTemplate,optional"`
	Variables       string `json:"variables,optional"`
	Type            string `json:"type,optional"`
}

type UnreadCountReq struct {
	UserId string `form:"userId"`
}

type UnreadCountResp struct {
	Count int64 `json:"count"`
}

// ===== 法师消息（master-scoped from JWT） =====

type MasterMessageListReq struct {
	IsRead int `form:"isRead,optional,default=-1"` // -1全部 0未读 1已读
	Page   int `form:"page,default=1"`
	Size   int `form:"size,default=20"`
}

type MasterMessageReadReq struct {
	Id int64 `path:"id"`
}
