// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: payment_booking.proto

package payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AutoPayBookingReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderNo        string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount         float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AutoPayBookingReq) Reset() {
	*x = AutoPayBookingReq{}
	mi := &file_payment_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoPayBookingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoPayBookingReq) ProtoMessage() {}

func (x *AutoPayBookingReq) ProtoReflect() protoreflect.Message {
	mi := &file_payment_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoPayBookingReq.ProtoReflect.Descriptor instead.
func (*AutoPayBookingReq) Descriptor() ([]byte, []int) {
	return file_payment_booking_proto_rawDescGZIP(), []int{0}
}

func (x *AutoPayBookingReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *AutoPayBookingReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AutoPayBookingReq) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AutoPayBookingReq) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type GetOrderPaymentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderType     string                 `protobuf:"bytes,1,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderPaymentReq) Reset() {
	*x = GetOrderPaymentReq{}
	mi := &file_payment_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderPaymentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderPaymentReq) ProtoMessage() {}

func (x *GetOrderPaymentReq) ProtoReflect() protoreflect.Message {
	mi := &file_payment_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderPaymentReq.ProtoReflect.Descriptor instead.
func (*GetOrderPaymentReq) Descriptor() ([]byte, []int) {
	return file_payment_booking_proto_rawDescGZIP(), []int{1}
}

func (x *GetOrderPaymentReq) GetOrderType() string {
	if x != nil {
		return x.OrderType
	}
	return ""
}

func (x *GetOrderPaymentReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type BookingPayment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PaymentNo     string                 `protobuf:"bytes,2,opt,name=payment_no,json=paymentNo,proto3" json:"payment_no,omitempty"`
	OrderType     string                 `protobuf:"bytes,3,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	OrderNo       string                 `protobuf:"bytes,4,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	Amount        float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Channel       string                 `protobuf:"bytes,6,opt,name=channel,proto3" json:"channel,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	TradeNo       string                 `protobuf:"bytes,8,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`
	Simulated     bool                   `protobuf:"varint,9,opt,name=simulated,proto3" json:"simulated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingPayment) Reset() {
	*x = BookingPayment{}
	mi := &file_payment_booking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingPayment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingPayment) ProtoMessage() {}

func (x *BookingPayment) ProtoReflect() protoreflect.Message {
	mi := &file_payment_booking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingPayment.ProtoReflect.Descriptor instead.
func (*BookingPayment) Descriptor() ([]byte, []int) {
	return file_payment_booking_proto_rawDescGZIP(), []int{2}
}

func (x *BookingPayment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BookingPayment) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

func (x *BookingPayment) GetOrderType() string {
	if x != nil {
		return x.OrderType
	}
	return ""
}

func (x *BookingPayment) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *BookingPayment) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BookingPayment) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *BookingPayment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BookingPayment) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *BookingPayment) GetSimulated() bool {
	if x != nil {
		return x.Simulated
	}
	return false
}

var File_payment_booking_proto protoreflect.FileDescriptor

const file_payment_booking_proto_rawDesc = "" +
	"\n" +
	"\x15payment_booking.proto\x12\apayment\"\x88\x01\n" +
	"\x11AutoPayBookingReq\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\"N\n" +
	"\x12GetOrderPaymentReq\x12\x1d\n" +
	"\n" +
	"order_type\x18\x01 \x01(\tR\torderType\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\"\xfc\x01\n" +
	"\x0eBookingPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"payment_no\x18\x02 \x01(\tR\tpaymentNo\x12\x1d\n" +
	"\n" +
	"order_type\x18\x03 \x01(\tR\torderType\x12\x19\n" +
	"\border_no\x18\x04 \x01(\tR\aorderNo\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12\x18\n" +
	"\achannel\x18\x06 \x01(\tR\achannel\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x19\n" +
	"\btrade_no\x18\b \x01(\tR\atradeNo\x12\x1c\n" +
	"\tsimulated\x18\t \x01(\bR\tsimulated2\xa7\x01\n" +
	"\x15PaymentBookingService\x12E\n" +
	"\x0eAutoPayBooking\x12\x1a.payment.AutoPayBookingReq\x1a\x17.payment.BookingPayment\x12G\n" +
	"\x0fGetOrderPayment\x12\x1b.payment.GetOrderPaymentReq\x1a\x17.payment.BookingPaymentB\x13Z\x11./payment;paymentb\x06proto3"

var (
	file_payment_booking_proto_rawDescOnce sync.Once
	file_payment_booking_proto_rawDescData []byte
)

func file_payment_booking_proto_rawDescGZIP() []byte {
	file_payment_booking_proto_rawDescOnce.Do(func() {
		file_payment_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_booking_proto_rawDesc), len(file_payment_booking_proto_rawDesc)))
	})
	return file_payment_booking_proto_rawDescData
}

var file_payment_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_payment_booking_proto_goTypes = []any{
	(*AutoPayBookingReq)(nil),  // 0: payment.AutoPayBookingReq
	(*GetOrderPaymentReq)(nil), // 1: payment.GetOrderPaymentReq
	(*BookingPayment)(nil),     // 2: payment.BookingPayment
}
var file_payment_booking_proto_depIdxs = []int32{
	0, // 0: payment.PaymentBookingService.AutoPayBooking:input_type -> payment.AutoPayBookingReq
	1, // 1: payment.PaymentBookingService.GetOrderPayment:input_type -> payment.GetOrderPaymentReq
	2, // 2: payment.PaymentBookingService.AutoPayBooking:output_type -> payment.BookingPayment
	2, // 3: payment.PaymentBookingService.GetOrderPayment:output_type -> payment.BookingPayment
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_payment_booking_proto_init() }
func file_payment_booking_proto_init() {
	if File_payment_booking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_booking_proto_rawDesc), len(file_payment_booking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_booking_proto_goTypes,
		DependencyIndexes: file_payment_booking_proto_depIdxs,
		MessageInfos:      file_payment_booking_proto_msgTypes,
	}.Build()
	File_payment_booking_proto = out.File
	file_payment_booking_proto_goTypes = nil
	file_payment_booking_proto_depIdxs = nil
}
