// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: payment_booking.proto

package payment

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentBookingService_AutoPayBooking_FullMethodName  = "/payment.PaymentBookingService/AutoPayBooking"
	PaymentBookingService_GetOrderPayment_FullMethodName = "/payment.PaymentBookingService/GetOrderPayment"
)

// PaymentBookingServiceClient is the client API for PaymentBookingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentBookingServiceClient interface {
	AutoPayBooking(ctx context.Context, in *AutoPayBookingReq, opts ...grpc.CallOption) (*BookingPayment, error)
	GetOrderPayment(ctx context.Context, in *GetOrderPaymentReq, opts ...grpc.CallOption) (*BookingPayment, error)
}

type paymentBookingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentBookingServiceClient(cc grpc.ClientConnInterface) PaymentBookingServiceClient {
	return &paymentBookingServiceClient{cc}
}

func (c *paymentBookingServiceClient) AutoPayBooking(ctx context.Context, in *AutoPayBookingReq, opts ...grpc.CallOption) (*BookingPayment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookingPayment)
	err := c.cc.Invoke(ctx, PaymentBookingService_AutoPayBooking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentBookingServiceClient) GetOrderPayment(ctx context.Context, in *GetOrderPaymentReq, opts ...grpc.CallOption) (*BookingPayment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookingPayment)
	err := c.cc.Invoke(ctx, PaymentBookingService_GetOrderPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentBookingServiceServer is the server API for PaymentBookingService service.
// All implementations must embed UnimplementedPaymentBookingServiceServer
// for forward compatibility.
type PaymentBookingServiceServer interface {
	AutoPayBooking(context.Context, *AutoPayBookingReq) (*BookingPayment, error)
	GetOrderPayment(context.Context, *GetOrderPaymentReq) (*BookingPayment, error)
	mustEmbedUnimplementedPaymentBookingServiceServer()
}

// UnimplementedPaymentBookingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentBookingServiceServer struct{}

func (UnimplementedPaymentBookingServiceServer) AutoPayBooking(context.Context, *AutoPayBookingReq) (*BookingPayment, error) {
	return nil, status.Error(codes.Unimplemented, "method AutoPayBooking not implemented")
}
func (UnimplementedPaymentBookingServiceServer) GetOrderPayment(context.Context, *GetOrderPaymentReq) (*BookingPayment, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrderPayment not implemented")
}
func (UnimplementedPaymentBookingServiceServer) mustEmbedUnimplementedPaymentBookingServiceServer() {}
func (UnimplementedPaymentBookingServiceServer) testEmbeddedByValue()                               {}

// UnsafePaymentBookingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentBookingServiceServer will
// result in compilation errors.
type UnsafePaymentBookingServiceServer interface {
	mustEmbedUnimplementedPaymentBookingServiceServer()
}

func RegisterPaymentBookingServiceServer(s grpc.ServiceRegistrar, srv PaymentBookingServiceServer) {
	// If the following call panics, it indicates UnimplementedPaymentBookingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentBookingService_ServiceDesc, srv)
}

func _PaymentBookingService_AutoPayBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AutoPayBookingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentBookingServiceServer).AutoPayBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentBookingService_AutoPayBooking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentBookingServiceServer).AutoPayBooking(ctx, req.(*AutoPayBookingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentBookingService_GetOrderPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderPaymentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentBookingServiceServer).GetOrderPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentBookingService_GetOrderPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentBookingServiceServer).GetOrderPayment(ctx, req.(*GetOrderPaymentReq))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentBookingService_ServiceDesc is the grpc.ServiceDesc for PaymentBookingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentBookingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment.PaymentBookingService",
	HandlerType: (*PaymentBookingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AutoPayBooking",
			Handler:    _PaymentBookingService_AutoPayBooking_Handler,
		},
		{
			MethodName: "GetOrderPayment",
			Handler:    _PaymentBookingService_GetOrderPayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment_booking.proto",
}
