// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: rpc/catalog/catalog.proto

package catalog

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CartLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	SkuId         int64                  `protobuf:"varint,2,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartLine) Reset() {
	*x = CartLine{}
	mi := &file_rpc_catalog_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartLine) ProtoMessage() {}

func (x *CartLine) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_catalog_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartLine.ProtoReflect.Descriptor instead.
func (*CartLine) Descriptor() ([]byte, []int) {
	return file_rpc_catalog_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *CartLine) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CartLine) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *CartLine) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CatalogQuote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	SkuId         int64                  `protobuf:"varint,2,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,3,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	SkuSpec       string                 `protobuf:"bytes,4,opt,name=sku_spec,json=skuSpec,proto3" json:"sku_spec,omitempty"`
	UnitPrice     float64                `protobuf:"fixed64,5,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	Quantity      int32                  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Image         string                 `protobuf:"bytes,7,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatalogQuote) Reset() {
	*x = CatalogQuote{}
	mi := &file_rpc_catalog_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogQuote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogQuote) ProtoMessage() {}

func (x *CatalogQuote) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_catalog_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogQuote.ProtoReflect.Descriptor instead.
func (*CatalogQuote) Descriptor() ([]byte, []int) {
	return file_rpc_catalog_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *CatalogQuote) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CatalogQuote) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *CatalogQuote) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *CatalogQuote) GetSkuSpec() string {
	if x != nil {
		return x.SkuSpec
	}
	return ""
}

func (x *CatalogQuote) GetUnitPrice() float64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *CatalogQuote) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CatalogQuote) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type ReserveCartReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Items         []*CartLine            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveCartReq) Reset() {
	*x = ReserveCartReq{}
	mi := &file_rpc_catalog_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveCartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveCartReq) ProtoMessage() {}

func (x *ReserveCartReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_catalog_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveCartReq.ProtoReflect.Descriptor instead.
func (*ReserveCartReq) Descriptor() ([]byte, []int) {
	return file_rpc_catalog_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *ReserveCartReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ReserveCartReq) GetItems() []*CartLine {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReserveCartResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Items         []*CatalogQuote        `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveCartResp) Reset() {
	*x = ReserveCartResp{}
	mi := &file_rpc_catalog_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveCartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveCartResp) ProtoMessage() {}

func (x *ReserveCartResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_catalog_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveCartResp.ProtoReflect.Descriptor instead.
func (*ReserveCartResp) Descriptor() ([]byte, []int) {
	return file_rpc_catalog_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *ReserveCartResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ReserveCartResp) GetItems() []*CatalogQuote {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ReserveCartResp) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type ReleaseCartReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseCartReq) Reset() {
	*x = ReleaseCartReq{}
	mi := &file_rpc_catalog_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseCartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseCartReq) ProtoMessage() {}

func (x *ReleaseCartReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_catalog_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseCartReq.ProtoReflect.Descriptor instead.
func (*ReleaseCartReq) Descriptor() ([]byte, []int) {
	return file_rpc_catalog_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *ReleaseCartReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ReleaseCartResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Released      bool                   `protobuf:"varint,1,opt,name=released,proto3" json:"released,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseCartResp) Reset() {
	*x = ReleaseCartResp{}
	mi := &file_rpc_catalog_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseCartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseCartResp) ProtoMessage() {}

func (x *ReleaseCartResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_catalog_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseCartResp.ProtoReflect.Descriptor instead.
func (*ReleaseCartResp) Descriptor() ([]byte, []int) {
	return file_rpc_catalog_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *ReleaseCartResp) GetReleased() bool {
	if x != nil {
		return x.Released
	}
	return false
}

var File_rpc_catalog_catalog_proto protoreflect.FileDescriptor

const file_rpc_catalog_catalog_proto_rawDesc = "" +
	"\n" +
	"\x19rpc/catalog/catalog.proto\x12\acatalog\"\\\n" +
	"\bCartLine\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x15\n" +
	"\x06sku_id\x18\x02 \x01(\x03R\x05skuId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"\xd3\x01\n" +
	"\fCatalogQuote\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x15\n" +
	"\x06sku_id\x18\x02 \x01(\x03R\x05skuId\x12!\n" +
	"\fproduct_name\x18\x03 \x01(\tR\vproductName\x12\x19\n" +
	"\bsku_spec\x18\x04 \x01(\tR\askuSpec\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x05 \x01(\x01R\tunitPrice\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05image\x18\a \x01(\tR\x05image\"X\n" +
	"\x0eReserveCartReq\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12'\n" +
	"\x05items\x18\x02 \x03(\v2\x11.catalog.CartLineR\x05items\"\x80\x01\n" +
	"\x0fReserveCartResp\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12+\n" +
	"\x05items\x18\x02 \x03(\v2\x15.catalog.CatalogQuoteR\x05items\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x01R\vtotalAmount\"/\n" +
	"\x0eReleaseCartReq\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"-\n" +
	"\x0fReleaseCartResp\x12\x1a\n" +
	"\breleased\x18\x01 \x01(\bR\breleased2\x94\x01\n" +
	"\x0eCatalogService\x12@\n" +
	"\vReserveCart\x12\x17.catalog.ReserveCartReq\x1a\x18.catalog.ReserveCartResp\x12@\n" +
	"\vReleaseCart\x12\x17.catalog.ReleaseCartReq\x1a\x18.catalog.ReleaseCartRespB/Z-github.com/askxuan/common/rpc/catalog;catalogb\x06proto3"

var (
	file_rpc_catalog_catalog_proto_rawDescOnce sync.Once
	file_rpc_catalog_catalog_proto_rawDescData []byte
)

func file_rpc_catalog_catalog_proto_rawDescGZIP() []byte {
	file_rpc_catalog_catalog_proto_rawDescOnce.Do(func() {
		file_rpc_catalog_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_catalog_catalog_proto_rawDesc), len(file_rpc_catalog_catalog_proto_rawDesc)))
	})
	return file_rpc_catalog_catalog_proto_rawDescData
}

var file_rpc_catalog_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rpc_catalog_catalog_proto_goTypes = []any{
	(*CartLine)(nil),        // 0: catalog.CartLine
	(*CatalogQuote)(nil),    // 1: catalog.CatalogQuote
	(*ReserveCartReq)(nil),  // 2: catalog.ReserveCartReq
	(*ReserveCartResp)(nil), // 3: catalog.ReserveCartResp
	(*ReleaseCartReq)(nil),  // 4: catalog.ReleaseCartReq
	(*ReleaseCartResp)(nil), // 5: catalog.ReleaseCartResp
}
var file_rpc_catalog_catalog_proto_depIdxs = []int32{
	0, // 0: catalog.ReserveCartReq.items:type_name -> catalog.CartLine
	1, // 1: catalog.ReserveCartResp.items:type_name -> catalog.CatalogQuote
	2, // 2: catalog.CatalogService.ReserveCart:input_type -> catalog.ReserveCartReq
	4, // 3: catalog.CatalogService.ReleaseCart:input_type -> catalog.ReleaseCartReq
	3, // 4: catalog.CatalogService.ReserveCart:output_type -> catalog.ReserveCartResp
	5, // 5: catalog.CatalogService.ReleaseCart:output_type -> catalog.ReleaseCartResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_catalog_catalog_proto_init() }
func file_rpc_catalog_catalog_proto_init() {
	if File_rpc_catalog_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_catalog_catalog_proto_rawDesc), len(file_rpc_catalog_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_catalog_catalog_proto_goTypes,
		DependencyIndexes: file_rpc_catalog_catalog_proto_depIdxs,
		MessageInfos:      file_rpc_catalog_catalog_proto_msgTypes,
	}.Build()
	File_rpc_catalog_catalog_proto = out.File
	file_rpc_catalog_catalog_proto_goTypes = nil
	file_rpc_catalog_catalog_proto_depIdxs = nil
}
