// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"github.com/askxuan/common/middleware"
	announcement "github.com/askxuan/message-service/internal/handler/announcement"
	message "github.com/askxuan/message-service/internal/handler/message"
	messageadmin "github.com/askxuan/message-service/internal/handler/messageadmin"
	messageadminannouncement "github.com/askxuan/message-service/internal/handler/messageadminannouncement"
	messagecustomer "github.com/askxuan/message-service/internal/handler/messagecustomer"
	messagemaster "github.com/askxuan/message-service/internal/handler/messagemaster"
	"github.com/askxuan/message-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	// JWT 鉴权配置（法师消息接口需要登录）
	authCfg := &middleware.AuthConfig{Secret: serverCtx.Config.AuthSecret}

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: announcement.AnnouncementListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/announcements"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPut,
				Path:    "/:id/read",
				Handler: message.ReadHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: message.ListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/messages"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/push",
				Handler: messageadmin.AdminPushHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/push-logs",
				Handler: messageadmin.AdminPushLogListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/templates",
				Handler: messageadmin.AdminTemplateListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/templates",
				Handler: messageadmin.AdminTemplateCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/templates/:id",
				Handler: messageadmin.AdminTemplateUpdateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/admin/messages"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPut,
				Path:    "/:id/status",
				Handler: messageadminannouncement.AdminAnnouncementStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: messageadminannouncement.AdminAnnouncementCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: messageadminannouncement.AdminAnnouncementListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/admin/announcements"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/device-token",
				Handler: messagecustomer.RegisterDeviceTokenHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/device-token",
				Handler: messagecustomer.UnbindDeviceTokenHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/:id",
				Handler: messagecustomer.DeleteMessageHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/read-all",
				Handler: messagecustomer.ReadAllHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/send",
				Handler: messagecustomer.SendMessageHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/unread-count",
				Handler: messagecustomer.UnreadCountHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/messages"),
	)

	// ===== 法师消息分组（需JWT） =====
	server.AddRoutes(
		rest.WithMiddleware(authCfg.AuthFunc, []rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: messagemaster.MasterMessageListHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/:id/read",
				Handler: messagemaster.MasterMessageReadHandler(serverCtx),
			},
		}...),
		rest.WithPrefix("/api/v1/admin/messages/master"),
	)

	// OpenIM webhook 回调（无 JWT 鉴权，由网关白名单放行）
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/openim/webhook",
				Handler: OpenIMWebhookHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/openim/webhook/:command",
				Handler: OpenIMWebhookHandler(serverCtx),
			},
		},
	)
}
