// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	announcement "github.com/askxuan/message-service/internal/handler/announcement"
	message "github.com/askxuan/message-service/internal/handler/message"
	messageadmin "github.com/askxuan/message-service/internal/handler/messageadmin"
	messageadminannouncement "github.com/askxuan/message-service/internal/handler/messageadminannouncement"
	messagecustomer "github.com/askxuan/message-service/internal/handler/messagecustomer"
	"github.com/askxuan/message-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: announcement.AnnouncementListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/announcements"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPut,
				Path:    "/:id/read",
				Handler: message.ReadHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: message.ListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/message"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/push",
				Handler: messageadmin.AdminPushHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/templates",
				Handler: messageadmin.AdminTemplateListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/templates",
				Handler: messageadmin.AdminTemplateCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/templates/:id",
				Handler: messageadmin.AdminTemplateUpdateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/admin/messages"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPut,
				Path:    "/:id/status",
				Handler: messageadminannouncement.AdminAnnouncementStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: messageadminannouncement.AdminAnnouncementCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: messageadminannouncement.AdminAnnouncementListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/admin/announcements"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodDelete,
				Path:    "/:id",
				Handler: messagecustomer.DeleteMessageHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/read-all",
				Handler: messagecustomer.ReadAllHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/unread-count",
				Handler: messagecustomer.UnreadCountHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/messages"),
	)
}
