// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: api/diy.proto

package diy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DiyService_GetBlessingTask_FullMethodName          = "/diy.DiyService/GetBlessingTask"
	DiyService_GetBlessingTaskByOrderNo_FullMethodName = "/diy.DiyService/GetBlessingTaskByOrderNo"
	DiyService_GetBlessingTaskByTaskNo_FullMethodName  = "/diy.DiyService/GetBlessingTaskByTaskNo"
	DiyService_ListBlessingTasks_FullMethodName        = "/diy.DiyService/ListBlessingTasks"
	DiyService_UpdateBlessingTaskStatus_FullMethodName = "/diy.DiyService/UpdateBlessingTaskStatus"
	DiyService_CompleteBlessingTask_FullMethodName     = "/diy.DiyService/CompleteBlessingTask"
	DiyService_AssignBlessingTask_FullMethodName       = "/diy.DiyService/AssignBlessingTask"
)

// DiyServiceClient is the client API for DiyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiyServiceClient interface {
	GetBlessingTask(ctx context.Context, in *GetBlessingTaskReq, opts ...grpc.CallOption) (*BlessingTask, error)
	GetBlessingTaskByOrderNo(ctx context.Context, in *GetBlessingTaskByOrderNoReq, opts ...grpc.CallOption) (*BlessingTask, error)
	GetBlessingTaskByTaskNo(ctx context.Context, in *GetBlessingTaskByTaskNoReq, opts ...grpc.CallOption) (*BlessingTask, error)
	ListBlessingTasks(ctx context.Context, in *ListBlessingTasksReq, opts ...grpc.CallOption) (*ListBlessingTasksResp, error)
	UpdateBlessingTaskStatus(ctx context.Context, in *UpdateBlessingTaskStatusReq, opts ...grpc.CallOption) (*BlessingTask, error)
	CompleteBlessingTask(ctx context.Context, in *CompleteBlessingTaskReq, opts ...grpc.CallOption) (*BlessingTask, error)
	AssignBlessingTask(ctx context.Context, in *AssignBlessingTaskReq, opts ...grpc.CallOption) (*BlessingTask, error)
}

type diyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDiyServiceClient(cc grpc.ClientConnInterface) DiyServiceClient {
	return &diyServiceClient{cc}
}

func (c *diyServiceClient) GetBlessingTask(ctx context.Context, in *GetBlessingTaskReq, opts ...grpc.CallOption) (*BlessingTask, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlessingTask)
	err := c.cc.Invoke(ctx, DiyService_GetBlessingTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diyServiceClient) GetBlessingTaskByOrderNo(ctx context.Context, in *GetBlessingTaskByOrderNoReq, opts ...grpc.CallOption) (*BlessingTask, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlessingTask)
	err := c.cc.Invoke(ctx, DiyService_GetBlessingTaskByOrderNo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diyServiceClient) GetBlessingTaskByTaskNo(ctx context.Context, in *GetBlessingTaskByTaskNoReq, opts ...grpc.CallOption) (*BlessingTask, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlessingTask)
	err := c.cc.Invoke(ctx, DiyService_GetBlessingTaskByTaskNo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diyServiceClient) ListBlessingTasks(ctx context.Context, in *ListBlessingTasksReq, opts ...grpc.CallOption) (*ListBlessingTasksResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBlessingTasksResp)
	err := c.cc.Invoke(ctx, DiyService_ListBlessingTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diyServiceClient) UpdateBlessingTaskStatus(ctx context.Context, in *UpdateBlessingTaskStatusReq, opts ...grpc.CallOption) (*BlessingTask, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlessingTask)
	err := c.cc.Invoke(ctx, DiyService_UpdateBlessingTaskStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diyServiceClient) CompleteBlessingTask(ctx context.Context, in *CompleteBlessingTaskReq, opts ...grpc.CallOption) (*BlessingTask, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlessingTask)
	err := c.cc.Invoke(ctx, DiyService_CompleteBlessingTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diyServiceClient) AssignBlessingTask(ctx context.Context, in *AssignBlessingTaskReq, opts ...grpc.CallOption) (*BlessingTask, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlessingTask)
	err := c.cc.Invoke(ctx, DiyService_AssignBlessingTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiyServiceServer is the server API for DiyService service.
// All implementations must embed UnimplementedDiyServiceServer
// for forward compatibility.
type DiyServiceServer interface {
	GetBlessingTask(context.Context, *GetBlessingTaskReq) (*BlessingTask, error)
	GetBlessingTaskByOrderNo(context.Context, *GetBlessingTaskByOrderNoReq) (*BlessingTask, error)
	GetBlessingTaskByTaskNo(context.Context, *GetBlessingTaskByTaskNoReq) (*BlessingTask, error)
	ListBlessingTasks(context.Context, *ListBlessingTasksReq) (*ListBlessingTasksResp, error)
	UpdateBlessingTaskStatus(context.Context, *UpdateBlessingTaskStatusReq) (*BlessingTask, error)
	CompleteBlessingTask(context.Context, *CompleteBlessingTaskReq) (*BlessingTask, error)
	AssignBlessingTask(context.Context, *AssignBlessingTaskReq) (*BlessingTask, error)
	mustEmbedUnimplementedDiyServiceServer()
}

// UnimplementedDiyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDiyServiceServer struct{}

func (UnimplementedDiyServiceServer) GetBlessingTask(context.Context, *GetBlessingTaskReq) (*BlessingTask, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlessingTask not implemented")
}
func (UnimplementedDiyServiceServer) GetBlessingTaskByOrderNo(context.Context, *GetBlessingTaskByOrderNoReq) (*BlessingTask, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlessingTaskByOrderNo not implemented")
}
func (UnimplementedDiyServiceServer) GetBlessingTaskByTaskNo(context.Context, *GetBlessingTaskByTaskNoReq) (*BlessingTask, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlessingTaskByTaskNo not implemented")
}
func (UnimplementedDiyServiceServer) ListBlessingTasks(context.Context, *ListBlessingTasksReq) (*ListBlessingTasksResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBlessingTasks not implemented")
}
func (UnimplementedDiyServiceServer) UpdateBlessingTaskStatus(context.Context, *UpdateBlessingTaskStatusReq) (*BlessingTask, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBlessingTaskStatus not implemented")
}
func (UnimplementedDiyServiceServer) CompleteBlessingTask(context.Context, *CompleteBlessingTaskReq) (*BlessingTask, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteBlessingTask not implemented")
}
func (UnimplementedDiyServiceServer) AssignBlessingTask(context.Context, *AssignBlessingTaskReq) (*BlessingTask, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignBlessingTask not implemented")
}
func (UnimplementedDiyServiceServer) mustEmbedUnimplementedDiyServiceServer() {}
func (UnimplementedDiyServiceServer) testEmbeddedByValue()                    {}

// UnsafeDiyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiyServiceServer will
// result in compilation errors.
type UnsafeDiyServiceServer interface {
	mustEmbedUnimplementedDiyServiceServer()
}

func RegisterDiyServiceServer(s grpc.ServiceRegistrar, srv DiyServiceServer) {
	// If the following call panics, it indicates UnimplementedDiyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DiyService_ServiceDesc, srv)
}

func _DiyService_GetBlessingTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlessingTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiyServiceServer).GetBlessingTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiyService_GetBlessingTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiyServiceServer).GetBlessingTask(ctx, req.(*GetBlessingTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiyService_GetBlessingTaskByOrderNo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlessingTaskByOrderNoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiyServiceServer).GetBlessingTaskByOrderNo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiyService_GetBlessingTaskByOrderNo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiyServiceServer).GetBlessingTaskByOrderNo(ctx, req.(*GetBlessingTaskByOrderNoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiyService_GetBlessingTaskByTaskNo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlessingTaskByTaskNoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiyServiceServer).GetBlessingTaskByTaskNo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiyService_GetBlessingTaskByTaskNo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiyServiceServer).GetBlessingTaskByTaskNo(ctx, req.(*GetBlessingTaskByTaskNoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiyService_ListBlessingTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBlessingTasksReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiyServiceServer).ListBlessingTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiyService_ListBlessingTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiyServiceServer).ListBlessingTasks(ctx, req.(*ListBlessingTasksReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiyService_UpdateBlessingTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBlessingTaskStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiyServiceServer).UpdateBlessingTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiyService_UpdateBlessingTaskStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiyServiceServer).UpdateBlessingTaskStatus(ctx, req.(*UpdateBlessingTaskStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiyService_CompleteBlessingTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteBlessingTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiyServiceServer).CompleteBlessingTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiyService_CompleteBlessingTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiyServiceServer).CompleteBlessingTask(ctx, req.(*CompleteBlessingTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiyService_AssignBlessingTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignBlessingTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiyServiceServer).AssignBlessingTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiyService_AssignBlessingTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiyServiceServer).AssignBlessingTask(ctx, req.(*AssignBlessingTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

// DiyService_ServiceDesc is the grpc.ServiceDesc for DiyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "diy.DiyService",
	HandlerType: (*DiyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlessingTask",
			Handler:    _DiyService_GetBlessingTask_Handler,
		},
		{
			MethodName: "GetBlessingTaskByOrderNo",
			Handler:    _DiyService_GetBlessingTaskByOrderNo_Handler,
		},
		{
			MethodName: "GetBlessingTaskByTaskNo",
			Handler:    _DiyService_GetBlessingTaskByTaskNo_Handler,
		},
		{
			MethodName: "ListBlessingTasks",
			Handler:    _DiyService_ListBlessingTasks_Handler,
		},
		{
			MethodName: "UpdateBlessingTaskStatus",
			Handler:    _DiyService_UpdateBlessingTaskStatus_Handler,
		},
		{
			MethodName: "CompleteBlessingTask",
			Handler:    _DiyService_CompleteBlessingTask_Handler,
		},
		{
			MethodName: "AssignBlessingTask",
			Handler:    _DiyService_AssignBlessingTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/diy.proto",
}
