// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: master_booking.proto

package master

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBookingMasterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MasterCode    string                 `protobuf:"bytes,1,opt,name=master_code,json=masterCode,proto3" json:"master_code,omitempty"`
	MasterId      int64                  `protobuf:"varint,2,opt,name=master_id,json=masterId,proto3" json:"master_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingMasterReq) Reset() {
	*x = GetBookingMasterReq{}
	mi := &file_master_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingMasterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingMasterReq) ProtoMessage() {}

func (x *GetBookingMasterReq) ProtoReflect() protoreflect.Message {
	mi := &file_master_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingMasterReq.ProtoReflect.Descriptor instead.
func (*GetBookingMasterReq) Descriptor() ([]byte, []int) {
	return file_master_booking_proto_rawDescGZIP(), []int{0}
}

func (x *GetBookingMasterReq) GetMasterCode() string {
	if x != nil {
		return x.MasterCode
	}
	return ""
}

func (x *GetBookingMasterReq) GetMasterId() int64 {
	if x != nil {
		return x.MasterId
	}
	return 0
}

type BookingMaster struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code           string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	DharmaName     string                 `protobuf:"bytes,3,opt,name=dharma_name,json=dharmaName,proto3" json:"dharma_name,omitempty"`
	TempleCode     string                 `protobuf:"bytes,4,opt,name=temple_code,json=templeCode,proto3" json:"temple_code,omitempty"`
	ShelfStatus    string                 `protobuf:"bytes,5,opt,name=shelf_status,json=shelfStatus,proto3" json:"shelf_status,omitempty"`
	PlatformStatus string                 `protobuf:"bytes,6,opt,name=platform_status,json=platformStatus,proto3" json:"platform_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BookingMaster) Reset() {
	*x = BookingMaster{}
	mi := &file_master_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingMaster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingMaster) ProtoMessage() {}

func (x *BookingMaster) ProtoReflect() protoreflect.Message {
	mi := &file_master_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingMaster.ProtoReflect.Descriptor instead.
func (*BookingMaster) Descriptor() ([]byte, []int) {
	return file_master_booking_proto_rawDescGZIP(), []int{1}
}

func (x *BookingMaster) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BookingMaster) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *BookingMaster) GetDharmaName() string {
	if x != nil {
		return x.DharmaName
	}
	return ""
}

func (x *BookingMaster) GetTempleCode() string {
	if x != nil {
		return x.TempleCode
	}
	return ""
}

func (x *BookingMaster) GetShelfStatus() string {
	if x != nil {
		return x.ShelfStatus
	}
	return ""
}

func (x *BookingMaster) GetPlatformStatus() string {
	if x != nil {
		return x.PlatformStatus
	}
	return ""
}

var File_master_booking_proto protoreflect.FileDescriptor

const file_master_booking_proto_rawDesc = "" +
	"\n" +
	"\x14master_booking.proto\x12\x06master\"S\n" +
	"\x13GetBookingMasterReq\x12\x1f\n" +
	"\vmaster_code\x18\x01 \x01(\tR\n" +
	"masterCode\x12\x1b\n" +
	"\tmaster_id\x18\x02 \x01(\x03R\bmasterId\"\xc1\x01\n" +
	"\rBookingMaster\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1f\n" +
	"\vdharma_name\x18\x03 \x01(\tR\n" +
	"dharmaName\x12\x1f\n" +
	"\vtemple_code\x18\x04 \x01(\tR\n" +
	"templeCode\x12!\n" +
	"\fshelf_status\x18\x05 \x01(\tR\vshelfStatus\x12'\n" +
	"\x0fplatform_status\x18\x06 \x01(\tR\x0eplatformStatus2^\n" +
	"\x14MasterBookingService\x12F\n" +
	"\x10GetBookingMaster\x12\x1b.master.GetBookingMasterReq\x1a\x15.master.BookingMasterB\x11Z\x0f./master;masterb\x06proto3"

var (
	file_master_booking_proto_rawDescOnce sync.Once
	file_master_booking_proto_rawDescData []byte
)

func file_master_booking_proto_rawDescGZIP() []byte {
	file_master_booking_proto_rawDescOnce.Do(func() {
		file_master_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_master_booking_proto_rawDesc), len(file_master_booking_proto_rawDesc)))
	})
	return file_master_booking_proto_rawDescData
}

var file_master_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_master_booking_proto_goTypes = []any{
	(*GetBookingMasterReq)(nil), // 0: master.GetBookingMasterReq
	(*BookingMaster)(nil),       // 1: master.BookingMaster
}
var file_master_booking_proto_depIdxs = []int32{
	0, // 0: master.MasterBookingService.GetBookingMaster:input_type -> master.GetBookingMasterReq
	1, // 1: master.MasterBookingService.GetBookingMaster:output_type -> master.BookingMaster
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_master_booking_proto_init() }
func file_master_booking_proto_init() {
	if File_master_booking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_master_booking_proto_rawDesc), len(file_master_booking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_master_booking_proto_goTypes,
		DependencyIndexes: file_master_booking_proto_depIdxs,
		MessageInfos:      file_master_booking_proto_msgTypes,
	}.Build()
	File_master_booking_proto = out.File
	file_master_booking_proto_goTypes = nil
	file_master_booking_proto_depIdxs = nil
}
