// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: temple_booking.proto

package temple

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TempleBookingService_GetBookingService_FullMethodName = "/temple.TempleBookingService/GetBookingService"
)

// TempleBookingServiceClient is the client API for TempleBookingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TempleBookingServiceClient interface {
	GetBookingService(ctx context.Context, in *GetBookingServiceReq, opts ...grpc.CallOption) (*BookingService, error)
}

type templeBookingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTempleBookingServiceClient(cc grpc.ClientConnInterface) TempleBookingServiceClient {
	return &templeBookingServiceClient{cc}
}

func (c *templeBookingServiceClient) GetBookingService(ctx context.Context, in *GetBookingServiceReq, opts ...grpc.CallOption) (*BookingService, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookingService)
	err := c.cc.Invoke(ctx, TempleBookingService_GetBookingService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TempleBookingServiceServer is the server API for TempleBookingService service.
// All implementations must embed UnimplementedTempleBookingServiceServer
// for forward compatibility.
type TempleBookingServiceServer interface {
	GetBookingService(context.Context, *GetBookingServiceReq) (*BookingService, error)
	mustEmbedUnimplementedTempleBookingServiceServer()
}

// UnimplementedTempleBookingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTempleBookingServiceServer struct{}

func (UnimplementedTempleBookingServiceServer) GetBookingService(context.Context, *GetBookingServiceReq) (*BookingService, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBookingService not implemented")
}
func (UnimplementedTempleBookingServiceServer) mustEmbedUnimplementedTempleBookingServiceServer() {}
func (UnimplementedTempleBookingServiceServer) testEmbeddedByValue()                              {}

// UnsafeTempleBookingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TempleBookingServiceServer will
// result in compilation errors.
type UnsafeTempleBookingServiceServer interface {
	mustEmbedUnimplementedTempleBookingServiceServer()
}

func RegisterTempleBookingServiceServer(s grpc.ServiceRegistrar, srv TempleBookingServiceServer) {
	// If the following call panics, it indicates UnimplementedTempleBookingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TempleBookingService_ServiceDesc, srv)
}

func _TempleBookingService_GetBookingService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookingServiceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TempleBookingServiceServer).GetBookingService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TempleBookingService_GetBookingService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TempleBookingServiceServer).GetBookingService(ctx, req.(*GetBookingServiceReq))
	}
	return interceptor(ctx, in, info, handler)
}

// TempleBookingService_ServiceDesc is the grpc.ServiceDesc for TempleBookingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TempleBookingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "temple.TempleBookingService",
	HandlerType: (*TempleBookingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBookingService",
			Handler:    _TempleBookingService_GetBookingService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "temple_booking.proto",
}
