// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: temple_booking.proto

package temple

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BookingSlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	StartTime     string                 `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Capacity      int64                  `protobuf:"varint,5,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingSlot) Reset() {
	*x = BookingSlot{}
	mi := &file_temple_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingSlot) ProtoMessage() {}

func (x *BookingSlot) ProtoReflect() protoreflect.Message {
	mi := &file_temple_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingSlot.ProtoReflect.Descriptor instead.
func (*BookingSlot) Descriptor() ([]byte, []int) {
	return file_temple_booking_proto_rawDescGZIP(), []int{0}
}

func (x *BookingSlot) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *BookingSlot) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *BookingSlot) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *BookingSlot) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *BookingSlot) GetCapacity() int64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *BookingSlot) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetBookingServiceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TempleCode    string                 `protobuf:"bytes,1,opt,name=temple_code,json=templeCode,proto3" json:"temple_code,omitempty"`
	ServiceCode   string                 `protobuf:"bytes,2,opt,name=service_code,json=serviceCode,proto3" json:"service_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingServiceReq) Reset() {
	*x = GetBookingServiceReq{}
	mi := &file_temple_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingServiceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingServiceReq) ProtoMessage() {}

func (x *GetBookingServiceReq) ProtoReflect() protoreflect.Message {
	mi := &file_temple_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingServiceReq.ProtoReflect.Descriptor instead.
func (*GetBookingServiceReq) Descriptor() ([]byte, []int) {
	return file_temple_booking_proto_rawDescGZIP(), []int{1}
}

func (x *GetBookingServiceReq) GetTempleCode() string {
	if x != nil {
		return x.TempleCode
	}
	return ""
}

func (x *GetBookingServiceReq) GetServiceCode() string {
	if x != nil {
		return x.ServiceCode
	}
	return ""
}

type BookingService struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TempleCode    string                 `protobuf:"bytes,1,opt,name=temple_code,json=templeCode,proto3" json:"temple_code,omitempty"`
	TempleName    string                 `protobuf:"bytes,2,opt,name=temple_name,json=templeName,proto3" json:"temple_name,omitempty"`
	TempleStatus  string                 `protobuf:"bytes,3,opt,name=temple_status,json=templeStatus,proto3" json:"temple_status,omitempty"`
	ServiceCode   string                 `protobuf:"bytes,4,opt,name=service_code,json=serviceCode,proto3" json:"service_code,omitempty"`
	ServiceName   string                 `protobuf:"bytes,5,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Price         float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	ServiceStatus string                 `protobuf:"bytes,7,opt,name=service_status,json=serviceStatus,proto3" json:"service_status,omitempty"`
	Slots         []*BookingSlot         `protobuf:"bytes,8,rep,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingService) Reset() {
	*x = BookingService{}
	mi := &file_temple_booking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingService) ProtoMessage() {}

func (x *BookingService) ProtoReflect() protoreflect.Message {
	mi := &file_temple_booking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingService.ProtoReflect.Descriptor instead.
func (*BookingService) Descriptor() ([]byte, []int) {
	return file_temple_booking_proto_rawDescGZIP(), []int{2}
}

func (x *BookingService) GetTempleCode() string {
	if x != nil {
		return x.TempleCode
	}
	return ""
}

func (x *BookingService) GetTempleName() string {
	if x != nil {
		return x.TempleName
	}
	return ""
}

func (x *BookingService) GetTempleStatus() string {
	if x != nil {
		return x.TempleStatus
	}
	return ""
}

func (x *BookingService) GetServiceCode() string {
	if x != nil {
		return x.ServiceCode
	}
	return ""
}

func (x *BookingService) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *BookingService) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *BookingService) GetServiceStatus() string {
	if x != nil {
		return x.ServiceStatus
	}
	return ""
}

func (x *BookingService) GetSlots() []*BookingSlot {
	if x != nil {
		return x.Slots
	}
	return nil
}

var File_temple_booking_proto protoreflect.FileDescriptor

const file_temple_booking_proto_rawDesc = "" +
	"\n" +
	"\x14temple_booking.proto\x12\x06temple\"\xa5\x01\n" +
	"\vBookingSlot\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\tR\aendTime\x12\x1a\n" +
	"\bcapacity\x18\x05 \x01(\x03R\bcapacity\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"Z\n" +
	"\x14GetBookingServiceReq\x12\x1f\n" +
	"\vtemple_code\x18\x01 \x01(\tR\n" +
	"templeCode\x12!\n" +
	"\fservice_code\x18\x02 \x01(\tR\vserviceCode\"\xa5\x02\n" +
	"\x0eBookingService\x12\x1f\n" +
	"\vtemple_code\x18\x01 \x01(\tR\n" +
	"templeCode\x12\x1f\n" +
	"\vtemple_name\x18\x02 \x01(\tR\n" +
	"templeName\x12#\n" +
	"\rtemple_status\x18\x03 \x01(\tR\ftempleStatus\x12!\n" +
	"\fservice_code\x18\x04 \x01(\tR\vserviceCode\x12!\n" +
	"\fservice_name\x18\x05 \x01(\tR\vserviceName\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12%\n" +
	"\x0eservice_status\x18\a \x01(\tR\rserviceStatus\x12)\n" +
	"\x05slots\x18\b \x03(\v2\x13.temple.BookingSlotR\x05slots2a\n" +
	"\x14TempleBookingService\x12I\n" +
	"\x11GetBookingService\x12\x1c.temple.GetBookingServiceReq\x1a\x16.temple.BookingServiceB\x11Z\x0f./temple;templeb\x06proto3"

var (
	file_temple_booking_proto_rawDescOnce sync.Once
	file_temple_booking_proto_rawDescData []byte
)

func file_temple_booking_proto_rawDescGZIP() []byte {
	file_temple_booking_proto_rawDescOnce.Do(func() {
		file_temple_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_temple_booking_proto_rawDesc), len(file_temple_booking_proto_rawDesc)))
	})
	return file_temple_booking_proto_rawDescData
}

var file_temple_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_temple_booking_proto_goTypes = []any{
	(*BookingSlot)(nil),          // 0: temple.BookingSlot
	(*GetBookingServiceReq)(nil), // 1: temple.GetBookingServiceReq
	(*BookingService)(nil),       // 2: temple.BookingService
}
var file_temple_booking_proto_depIdxs = []int32{
	0, // 0: temple.BookingService.slots:type_name -> temple.BookingSlot
	1, // 1: temple.TempleBookingService.GetBookingService:input_type -> temple.GetBookingServiceReq
	2, // 2: temple.TempleBookingService.GetBookingService:output_type -> temple.BookingService
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_temple_booking_proto_init() }
func file_temple_booking_proto_init() {
	if File_temple_booking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_temple_booking_proto_rawDesc), len(file_temple_booking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_temple_booking_proto_goTypes,
		DependencyIndexes: file_temple_booking_proto_depIdxs,
		MessageInfos:      file_temple_booking_proto_msgTypes,
	}.Build()
	File_temple_booking_proto = out.File
	file_temple_booking_proto_goTypes = nil
	file_temple_booking_proto_depIdxs = nil
}
